% function setprintnice
% set plotting defaults to nice looking stuff
% Orignal code: John Turner
% Modified Oct. 15 by Kara Koetje

function setprintnice
set(0,'DefaultTextFontName','Times',...
'DefaultTextFontSize',18,...
'DefaultAxesFontName','Times',...
'DefaultAxesFontSize',18,...
'DefaultLineLineWidth',2,...
'DefaultLineMarkerSize',7.75,...
'DefaultTextInterpreter','Latex');
end